columns:
  Area: float
  BHK: int
  Bathroom: float
  Furnishing: category
  Locality: category
  Parking: float
  Price: int
  Status: category
  Transaction: category
  Type: category
  Per_Sqft: float

numerical_columns:
  - Area
  - BHK
  - Bathroom
  - Parking
  - Price
  - Per_Sqft

categorical_columns:
  - Furnishing
  - Locality
  - Status
  - Transaction
  - Type


# for data transformation
num_features:
  - Area
  - BHK
  - Bathroom
  - Parking
  - Per_Sqft


# mm_columns:
#   - Annual_Premium